package pt.cmg.jakartautils.jpa;

public class JpaQueryException extends RuntimeException {

    /**
     * Auto-generated by IDE
     */
    private static final long serialVersionUID = -288155323499347709L;

    public JpaQueryException(String message) {
        super(message);
    }

}
